name: basenji2-pytorch
channels:
  - conda-forge
  - nodefaults
dependencies:
  - einops
  - natsort
  - numpy
  - pytorch-lightning
  - pytorch::pytorch
  - torchinfo
  - torchmetrics
platforms:
  - linux-64
  - osx-64